# import Testing1.driver

import datetime

from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

from Testing6 import *

# baseURL = ReadConfig.getURL()
driver.get("http://192.168.0.33:8080/")
driver.maximize_window()
time.sleep(5)
# driver.execute_script("window.scrollBy(0,200000)", "")
# time.sleep(12)
# Landing = driver.find_element(By.XPATH, "//a[contains(text(),'here')]")
# Landing.click()
# time.sleep(1)


current_time = datetime.datetime.now()
today = current_time.day
Username = driver.find_element(By.XPATH, "//*[@formcontrolname='userName']")
Username.send_keys("jenny1")
# time.sleep(1)
Pw = driver.find_element(By.XPATH, "//*[@formcontrolname='password']")
Pw.send_keys("12345")
Login = driver.find_element(By.XPATH, "//*[contains(text(),'Login')]")
Login.click()
time.sleep(3)

Planning = driver.find_element(By.XPATH, "//span[contains(text(),'Planning')]")
Planning.click()
time.sleep(1)
Rule = driver.find_element(By.XPATH, "//span[text()='Loads']")
Rule.click()
time.sleep(1)
CreateRule = driver.find_element(By.XPATH, "//*[text()='Plan Load']")
CreateRule.click()
time.sleep(3)
Rule = driver.find_element(By.XPATH, "//*[text()=' Create New Workbench']")
Rule.click()
time.sleep(8)
OrderType = driver.find_element(By.XPATH, "//*[@formcontrolname='estimatedDateTypeETD']")
DateType = "Custom"
drp = Select(OrderType)
drp.select_by_visible_text(DateType)
time.sleep(2)

name = driver.find_element(By.XPATH, "// *[contains( @name, 'calendar')]")
name.click()
time.sleep(1)
# Descr = driver.find_element(By.XPATH, "(//*[@class='ngb-dp-navigation-chevron'])[1]")
# Descr.click()
# time.sleep(1)
month = "Feb"
Month_Select = driver.find_element(By.XPATH, "// *[contains( @ title, 'Select month')]")
drp = Select(Month_Select)
drp.select_by_visible_text(month)
time.sleep(2)
Next = driver.find_element(By.XPATH, "//span[normalize-space(text())='1']")
Next.click()
time.sleep(30)
# Next = driver.find_element(By.XPATH, "//*[@formcontrolname='hazLicenseNumber']")
# Next.click()
# time.sleep(30)
# a = ActionChains(driver)
# src = driver.find_element(By.XPATH, "(//*[text()='Order Date'])[1]")
# des = driver.find_element(By.XPATH, "//*[text()=' Origin Country Code']")
# time.sleep(1)
# a.click_and_hold(on_element=src).move_to_element(des).release(on_element=des).perform()
# Next = driver.find_element(By.XPATH, "(// *[contains(text(), ' Next ')])[2]")
# Next.click()
# time.sleep(2)
# src1 = driver.find_element(By.XPATH, "(//*[text()= 'HS Code'])[2]")
# des2 = driver.find_element(By.XPATH, "//*[@class='item']")
# a.click_and_hold(on_element=src1).move_to_element(des2).release(on_element=des2).perform()
# Search = driver.find_element(By.XPATH, "(//*[@placeholder='Search...'])[2]")
# Search.send_keys("aaa")

# a.drag_and_drop(b, des).perform()
# a = driver.current_url
# driver.execute_script('window.open("driver.get(a)")')
# a = driver.current_url
# driver.get(a)
# print(a)
# driver.switch_to.window(driver.window_handles[1])
# driver.get(a)
# driver.switch_to.window(driver.window_handles[0])

# action_chains = ActionChains(driver)
# action_chains.key_down(Keys.ALT).key_down(Keys.SHIFT).send_keys('d').perform()
# action_chains.key_up(Keys.ALT).key_up(Keys.SHIFT).perform()
# time.sleep(15)
# file = open(".//TestData//data.json", "r")
# finaldata = json.load(file)
# print(finaldata)
# print(finaldata['BagSeal'])
# a = finaldata['BagSeal']
# print(a)
# b = int(a) + 1
# print(b)
# c = b + 1
# print(c)

# time.sleep(3)
# Login = driver.find_element(By.XPATH, "//input[contains(@name,'Login')]")
# Login.click()
# time.sleep(3)
# # driver.execute_script("window.scrollBy(0,200000)", "")
# WebECbut = driver.find_element(By.XPATH, "//a[contains(text(),'webEC - Equipment Control')]")
# driver.execute_script("arguments[0].click()", WebECbut)
# time.sleep(1)
# # driver.switch_to.frame("mainPanel")
# # time.sleep(1)
# # driver.execute_script("window.scrollBy(0,200000)", "")
# # time.sleep(1)
# # av = driver.find_element(By.XPATH, "//a[contains(text(),'WebEC Utilities')]")
# # driver.execute_script("arguments[0].click()", av)
# # time.sleep(1)
# # av1 = driver.find_element(By.XPATH, "//a[contains(text(),'Mass Container Update')]")
# # driver.execute_script("arguments[0].click()", av1)
# # time.sleep(1)
# # av2 = driver.find_element(By.XPATH, "//select[contains(@class,'drop_down')]")
# # av2.click()
# # time.sleep(1)
# # av3 = driver.find_element(By.XPATH, "//*[contains(text(),'AMZ-LGB')]")
# # av3.click()
# # time.sleep(1)
# # av4 = driver.find_element(By.XPATH, "//select[contains(@class,'drop_down')]")
# # av4.click()
# # time.sleep(1)
# # av5 = driver.find_element(By.XPATH, "(//*[contains(text(),'AMZ')])[2]")
# # av5.click()
# # time.sleep(1)
# # av6 = driver.find_element(By.XPATH, "//*[contains(@name,'sContainer')]")
# # av6.send_keys("FSCU8163125")
# # time.sleep(1)
# # av7 = driver.find_element(By.XPATH, "//*[contains(@name,'btnSearch')]")
# # av7.click()
# # time.sleep(4)
# # driver.switch_to.default_content()
# driver.switch_to.frame("topPanel")
# time.sleep(1)
# av8 = driver.find_element(By.XPATH, "//*[contains(text(),'Home')]")
# av8.click()
# time.sleep(4)
# driver.switch_to.default_content()
# driver.switch_to.frame("mainPanel")
# time.sleep(1)
# av9 = driver.find_element(By.XPATH, "//a[contains(text(),'Equipment Control')]")
# av9.click()
# time.sleep(4)
# av10 = driver.find_element(By.XPATH, "//*[@name= 'sContainer']")
# av10.send_keys("FSCU8163125")
# # time.sleep(4)
# av11 = driver.find_element(By.XPATH, "//*[@name= 'btnContainer']")
# av11.click()
# time.sleep(4)
# av12 = driver.find_element(By.XPATH, "//*[contains(text(),'FSCU8163125')]")
# av12.click()
# time.sleep(4)
# action = ActionChains(driver)
# action.click_and_hold()
